### ISSUE TITLE
Use master branch on Krogoth

### ISSUE THREAD

**Issue by markov00** [OSSystems/meta-browser#108]
Hi, I'm quite new to Yocto and I was wondering if the master branch of chromium Wayland is somehow compatible with the Krogoth release.
What are the main compatibility checks I need to perform?
My current problem is that the board I'm using is a custom version of an imx6 and the hw provider doesn't want to update the compatibility of some of the drivers to a newer release of yocto.
I'm currently using chromium 48 with wayland but it has some performance issues.
Thanks

**Comment by otavio** [comment]
This is not intended or supported. If you decide to go this route you are on your own ;-)
