### ISSUE TITLE
Launching /usr/bin/chromium fails unless it has arg --no-sandbox 

### ISSUE THREAD

**Issue by cchilumbu** [OSSystems/meta-browser#133]
I am using branch ozone/wayland/67.0.33.., and recipe chromium-x11.bb

How can I invoke chromium without providing the "--no-sandbox" argument?

**Comment by rakuco** [comment]
That branch name does not exist here. Are you sure you're using the right repository?

**Comment by cchilumbu** [comment]
I beg your pardon, I should have directed this onto the Igalia site.

Thank you.
