### ISSUE TITLE
compile error on yocto project?

### ISSUE THREAD

**Issue by 13824125580** [OSSystems/meta-browser#134]
HI guys:
  i meet a problem when  do the compile operation on yocto project with command "bitbake chromium-ozone-wayland", the error verbose as follows:
[5/735] python ../../build/gn_run_binary.py yocto_native/transport_security_state_generator ../../net/http/transport_security_state_static.json ../../net/http/transport_security_state_static.pins ../../net/http/transport_security_state_static.template gen/net/http/transport_security_state_static.h
| FAILED: gen/net/http/transport_security_state_static.h

it seems somthing wrong happen when genenrate the automatic file transport_security_state_static.h, so 
how to dealt with this？

much appreciate your help.

**Comment by rakuco** [comment]
Which branch and `MACHINE` are you using? This is a tool that runs on the host side to generate some files, my guess is that the binary is missing a library dependency and failing to run.

**Comment by rakuco** [comment]
And what host are you using? The files should all really be there since they're part of the tarball, the problem as I said is that there's something going on when you run those native tools on your host.

You can also run devshell and try running that command manually from the right directory to get a more verbose error message.

**Comment by 13824125580** [comment]
thank you!
my host is "Ubuntu 14.04.4 LTS \n \l"
and i do the test as follow your advice in director "out/Release" of devshell, but it seems no more information besides "exit code -11"  :-(
ro ot@exdroid40:~/WorkSpace/yocto/build/tmp/work/aarch64-poky-linux-musl/chromium-ozone-wayland/64.0.3274.0.r517731.igalia.1-r0/chromium-ozone-wayland-dev-64.0.3274.0.r517731.igalia.1/out/Release# python ../../build/gn_run_binary.py yocto_native/transport_security_state_generator ../../net/http/transport_security_state_static.json ../../net/http/transport_security_state_static.pins ../../net/http/transport_security_state_static.template gen/net/http/transport_security_state_static.h
yocto_native/transport_security_state_generator failed with exit code -11

**Comment by rakuco** [comment]
Can you try running `transport_security_state_generator` without invoking python and the `../../build/gn_run_binary.py` wrapper?

**Comment by 13824125580** [comment]
oh, got the error message, the chinese output means "segment fault", seems crash happen, and i debug with strace -f, the output as follows. have ever meet this issue before？　seems native appliction problems. :-(

et_robust_list(0x7fcb1dec2a20, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7fcb1daacb50, [], SA_RESTORER|SA_SIGINFO, 0x7fcb1dab8390}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7fcb1daacbe0, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7fcb1dab8390}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7ffedacd5ff8} ---
+++ killed by SIGSEGV (core dumped) +++
段错误 (核心已转储)
caozilong@exdroid40:~/WorkSpace/yocto/build/tmp/work/aarch64-poky-linux-musl/chromium-ozone-wayland/64.0.3274.0.r517731.igalia.1-r0/chromium-ozone-wayland-dev-64.0.3274.0.r517731.igalia.1/out/Release$ ./yocto_native/transport_security_state_generator ../../net/http/transport_security_state_static.json ../../net/http/transport_security_state_static.pins ../../net/http/transport_security_state_static.template gen/net/http/transport_security_state_static.h
段错误 (核心已转储)

**Comment by rakuco** [comment]
Are you on a x86-64 host? Do any other binaries in `yocto_native/` run for you? It'd also be good to try to reproduce this with chromium-x11, though it really looks like something on your setup.

**Comment by caozilong** [comment]
my host is X86-64.
there are sever binaries in dir.
brotli  character_data_generator  flatc  gen  icudtl.dat  obj  protoc  toolchain.ninja  transport_security_state_generator

after test, transport_security_state_generator crashed even during "dry run" without parameter.
but others are ok.

why use "chromium-x11"? my target dispay backend is "wayland" and x11 cant support, so chromium-x11 project seems useless to me.

**Comment by rakuco** [comment]
> why use "chromium-x11"? my target dispay backend is "wayland" and x11 cant support, so chromium-x11 project seems useless to me.

To check if the problem persists on a much more recent Chromium version than chromium-ozone-wayland's M64.

**Comment by caozilong** [comment]
i try, but because of huge lake of dependent packages, compile cant go through.
did someone ever meet this before, or
 can you tell me a right environment to compile chromium-ozone-wayland pass through for compare?
thanks for your kindly support.

**Comment by rakuco** [comment]
I've always used Fedora x86-64 (multiple releases) as my host system, and others have mentioned using openSUSE and very likely Ubuntu as well.

**Comment by 13824125580** [comment]
by the way, if chromium-x11 compile passed  on another environment, did the "transport_security_state_generator " can be shared with wayland ?  is it work  to use the header files generated by the x11 compile process:?

**Comment by rakuco** [comment]
chromium-x11 is tracking a different Chromium release, so while the tool is still used for the same purpose there is no guarantee that code generated for Chromium 67 works with Chromium 64.
