### ISSUE TITLE
did firefox port support wayland backend?

### ISSUE THREAD

**Issue by 13824125580** [OSSystems/meta-browser#141]
did the firefox port of this repo suppport wayland-backend? as i know, the offical release of firefox supports wayland already.

**Comment by cosmo0920** [comment]
Our forked meta-browser tree is trying to support wayland.
https://github.com/webdino/meta-browser/tree/firefox-60esr
@ashie want to feedback our work but he seems to be busy now :(

**Comment by ashie** [comment]
TODO list: #128

**Comment by 13824125580** [comment]
thanks you all
