### ISSUE TITLE
how to open a website with by commandline?

### ISSUE THREAD

**Issue by 13824125580** [OSSystems/meta-browser#144]
haha!!!
the chromium-ozone-wayland  now can be run on my port.  thanks for your support.

but for my device has limitation input devices, is there any way to open a websit by chromium command line?
thanks !

**Comment by rakuco** [comment]
> the chromium-ozone-wayland now can be run on my port. thanks for your support.

Glad to hear that, please close any issues that are no longer blocking you.

> but for my device has limitation input devices, is there any way to open a websit by chromium command line?

Just passing the address should be fine (e.g. `chromium https://github.com`).

**Comment by 13824125580** [comment]
thank you.
