### ISSUE TITLE
where is the gpu process?

### ISSUE THREAD

**Issue by 13824125580** [OSSystems/meta-browser#148]
i got the process tree after launch the chromium process and open a website, 
i found there is only two process on the hierarchy of chromium, that is the browser(3211) and render (3265), as you see below.

that is not same like chromium on PC environments,  there would be a extra gpu process in the same scenario, so, what happens to chromium? is this mean the gpu  acceleration did not open?
thanks for your help.

 |-ash(1249)---chromium-bin(3204)-+-cat(3208)
        |                                |-cat(3209)
        |                                |-chromium-bin(3211)---chromium-bin(3265)-+-{Chrome_ChildIOT}(3271)
        |                                |                                         |-{CompositorTileW}(3278)
        |                                |                                         |-{CompositorTileW}(3279)
        |                                |                                         |-{CompositorTileW}(3280)
        |                                |                                         |-{Compositor}(3277)
        |                                |                                         |-{File}(3274)
        |                                |                                         |-{GpuMemoryThread}(3272)
        |                                |                                         |-{ScriptStreamerT}(3285)
        |                                |                                         |-{TaskSchedulerRe}(3267)
        |                                |                                         |-{TaskSchedulerRe}(3268)
        |                                |                                         |-{TaskSchedulerRe}(3269)
        |                                |                                         |-{TaskSchedulerRe}(3270)
        |                                |                                         |-{TaskSchedulerRe}(3282)
        |                                |                                         |-{TaskSchedulerRe}(3291)
        |                                |                                         |-{TaskSchedulerRe}(3292)
        |                                |                                         `-{TaskSchedulerSe}(3266)
        |                                |-{AudioThread}(3252)
        |                                |-{BrowserWatchdog}(3253)
        |                                |-{Chrome_HistoryT}(3257)
        |                                |-{Chrome_IOThread}(3234)
        |                                |-{CompositorThrea}(3251)
        |                                |-{CompositorTileW}(3241)
        |                                |-{CrShutdownDetec}(3215)
        |                                |-{D-Bus thread}(3213)
        |                                |-{GpuIOThread}(3250)
        |                                |-{GpuMemoryThread}(3240)
        |                                |-{GpuThread}(3246)
        |                                |-{GpuThread}(3247)
        |                                |-{GpuThread}(3248)
        |                                |-{GpuThread}(3249)
        |                                |-{NetworkChangeNo}(3212)
        |                                |-{Startup watchdo}(3262)
        |                                |-{TaskSchedulerBa}(3221)
        |                                |-{TaskSchedulerBa}(3222)
        |                                |-{TaskSchedulerBa}(3223)
        |                                |-{TaskSchedulerBa}(3224)
        |                                |-{TaskSchedulerFo}(3225)
        |                                |-{TaskSchedulerFo}(3226)
        |                                |-{TaskSchedulerFo}(3227)
        |                                |-{TaskSchedulerFo}(3228)
        |                                |-{TaskSchedulerFo}(3259)
        |                                |-{TaskSchedulerFo}(3260)
        |                                |-{TaskSchedulerFo}(3261)
        |                                |-{TaskSchedulerFo}(3273)
        |                                |-{TaskSchedulerSe}(3220)
        |                                |-{TaskSchedulerSi}(3229)
        |                                |-{TaskSchedulerSi}(3230)
        |                                |-{TaskSchedulerSi}(3231)
        |                                |-{TaskSchedulerSi}(3232)
        |                                |-{TaskSchedulerSi}(3233)
        |                                |-{TaskSchedulerSi}(3237)
        |                                |-{TaskSchedulerSi}(3256)
        |                                |-{inotify_reader}(3219)
        |                                |-{mus}(3245)
        |                                |-{renderer_crash_}(3264)
        |                                `-{sandbox_ipc_thr}(3210)

**Comment by msisov** [comment]
You are using Wayland recipe, aren't you? It's expected as long as the gpu split hasn't been merged yet. The work is ongoing. So, it's expected and chromium runs with in-process-gpu mode.

**Comment by 13824125580** [comment]
i am using chromium-ozone-wayland recipe.
did this mean the gpu acceleration did not eanbled? just using sofware render?

by the way, wayland not support seperate gpu process, is this the problem of the upstream of google? or  is the problem of the meta layer?

thanks for your kindly help.

**Comment by msisov** [comment]
it's accelerated graphics.

It's a problem of the upstream.

**Comment by 13824125580** [comment]
thank you.
