### ISSUE TITLE
is there any plan to update the chromium-ozone-wayland port to the latest version of igalia ?

### ISSUE THREAD

**Issue by 13824125580** [OSSystems/meta-browser#152]
seems we now use a older version of chromium ozone wayland port, is there any plan to update the recipe to the latest version?
  | Parent Directory |   | - |  
  | chromium-ozone-wayland-dev-64.0.3257.1.r513783.igalia.1.tar.xz | 2017-11-10 10:52 | 562M |  
  | chromium-ozone-wayland-dev-64.0.3267.0.r515863.igalia.1.tar.xz | 2017-11-16 21:07 | 544M |  
  | chromium-ozone-wayland-dev-64.0.3274.0.r517731.igalia.1.tar.xz | 2017-11-22 00:50 | 579M |  
  | chromium-ozone-wayland-dev-64.0.3278.0.r519194.igalia.1.tar.xz | 2017-11-30 12:56 | 585M |  
  | chromium-ozone-wayland-dev-65.0.3298.0.r524623.igalia.1.tar.xz | 2017-12-20 14:02 | 585M |  
  | chromium-ozone-wayland-dev-65.0.3315.0.r527534.igalia.1.tar.xz | 2018-01-12 17:00 | 634M |  
  | chromium-ozone-wayland-dev-66.0.3340.0.r534306.igalia.1.tar.xz | 2018-02-12 09:48 | 640M |  
  | chromium-ozone-wayland-dev-67.0.3361.0.r540770.igalia.1.tar.xz | 2018-03-07 13:56 | 706M |  
  | chromium-ozone-wayland-dev-67.0.3368.0.r542415.igalia.1.tar.xz | 2018-03-16 13:55 | 709M |  
  | chromium-ozone-wayland-dev-67.0.3375.0.r543955.igalia.1.tar.xz | 2018-03-19 15:54 | 709M |  
  | chromium-ozone-wayland-dev-67.0.3387.0.r547398.igalia.1.tar.xz | 2018-04-05 15:50 | 709M |  
  | chromium-ozone-wayland-dev-68.0.3404.0.r552606.igalia.1.tar.xz | 2018-05-24 12:01 | 2.3M |  
  | chromium-ozone-wayland-dev-68.0.3437.0.r560198.igalia.1.tar.xz | 2018-05-24 20:12 | 792M |  
  | chromium-ozone-wayland-dev-69.0.3448.0.r563980.igalia.1.tar.xz | 2018-06-04 18:21 | 806M |  
  | chromium-ozone-wayland-dev-69.0.3455.0.r565933.igalia.1.tar.xz | 2018-06-14 09:56 | 809M |  
  | chromium-ozone-wayland-dev-69.0.3474.0.r570340.igalia.1.tar.xz | 2018-06-26 15:45 | 815M |  
  | chromium-wayland-8eb8619a.tar.xz | 2018-03-06 12:37 | 1.8G |

**Comment by msisov** [comment]
yes. I'm working on it.

**Comment by 13824125580** [comment]
thank you
