### ISSUE TITLE
some website cat be reached issue.

### ISSUE THREAD

**Issue by 13824125580** [OSSystems/meta-browser#155]
hi guys:
   during the test i found some website cant be reached every time, for example  "http://www.baidu.com"
  cant be reached.

but most of the website cant be visit, such as:
http://html5test.com
http://www.ifent.com
http://www.qq.com

and so on , so, seems not the problem of the network,  is there any clue for this issue?

**Comment by otavio** [comment]
Does this still happen? It seems like a network issue and not a browser issue.

**Comment by otavio** [comment]
Closing due inactivity.
