### ISSUE TITLE
chromium 71 would not get into the kiosk mode 

### ISSUE THREAD

**Issue by 13824125580** [OSSystems/meta-browser#176]
hi folks:
i use the latest chromium ozone wayland port 71 in your igilia repo .
when i launch it with command"
chromium --no-sandbox --kiosk
and found that the address bar and tools menu still hung it and did not work in full screen mode.

that is different from the previous version of 70, so, is this expected?

**Comment by msisov** [comment]
Please file a bug in the correct repo.

**Comment by 13824125580** [comment]
@msisov 
could you tell me which place shall i file the bug?

**Comment by msisov** [comment]
I’d suggest to file a bug in the upstream bug tracker as long as the work is currently happens mostly there.

https://bugs.chromium.org/p/chromium/issues/list 

File a bug and add me (msisov@igalia.com) to CC.

**Comment by otavio** [comment]
This is clearly not related here, closing it.

**Comment by msisov** [comment]
And it’s fixed in the upstream, btw. The fix will be a part of m72 recipe
