### ISSUE TITLE
firefox master branch error

### ISSUE THREAD

**Issue by vsivanagulu** [OSSystems/meta-browser#178]
i have added meta-browser to my imx6 based BSP and I am using master branch firefox 52.9 i am getting below issue .

>  4.060937] [<c06a0dbc>] (dbs_work_handler) from [<c013bda0>] (process_one_work+0x1ec/0x414)
[    4.069395]  r9:00000000 r8:00000000 r7:ef7bb800 r6:ef7b8900 r5:ec5f5a80 r4:ec681438
[    4.077161] [<c013bbb4>] (process_one_work) from [<c013cba4>] (worker_thread+0x3c/0x600)
[    4.085271]  r10:c0e02d00 r9:ffffe000 r8:ef7b8918 r7:00000008 r6:ec5f5a98 r5:ef7b8900
[    4.093111]  r4:ec5f5a80
[    4.095666] [<c013cb68>] (worker_thread) from [<c0141ddc>] (kthread+0x14c/0x164)
[    4.103082]  r10:ec071e98 r9:c013cb68 r8:ec5f5a80 r7:ec634000 r6:ec614780 r5:ec09c940
[    4.110922]  r4:00000000
[    4.113485] [<c0141c90>] (kthread) from [<c0108108>] (ret_from_fork+0x14/0x2c)
[    4.120727]  r10:00000000 r9:00000000 r8:00000000 r7:00000000 r6:00000000 r5:c0141c90
[    4.128566]  r4:ec614780
[    4.131130] ---[ end Kernel panic - not syncing: No working init found.  Try passing init= option to kernel. See Linux Documentation/admin-

> 
NOTE: If i remove firefox then core-image-sato is working fine. only when I add firefox then error is occur. is there any special config require.

**Comment by otavio** [comment]
It is surprising. The error above is a kernel panic indicating it couldn't find a init service to start. Maybe adding firefox causes your rootfs to get bigger and cause the problem? I don't know, but it is a side effect for sure.

Either way, it is not related to meta-browser or i.MX general BSP support. Likely, something specific to your system.

I will close this issue for now.
