### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by level451** [OSSystems/meta-browser#184]
ParseError at /home/todd/poky/_toaster_clones/_https___github.com_OSSystems_meta-browser.git_master/recipes-browser/firefox/firefox_60.1.0esr.bb:67: Could not inherit file classes/rust-common.bbclass

I believe the last change broke it - any advice?

**Comment by otavio** [comment]
Yes, it now depends on the Rust layer. 

Is it possible for you to send a PR adding it on the list of dependencies of `conf/layer.conf` ?

**Comment by rakuco** [comment]
Fixed by #185
