### ISSUE TITLE
CEF3 Build

### ISSUE THREAD

**Issue by pl161187smi** [OSSystems/meta-browser#229]
Hello, please help me, how I can build cef3, may be anybody has some manual about how to add cef3 to my custom linux project, I use raspberry pi 3 and succesfully biild linux image with wayland, and now I want to add cef3 to this image build, I downgrade GCCVERSION to 5.4.0 but I have many error in build...
Thank you.Regards.

**Comment by rakuco** [comment]
We don't support CEF in this repository, and we do not provide a recipe for it here. #182 had a prototype recipe that we chose not to integrate, perhaps you could you use it as a starting point for your work.

**Comment by pl161187smi** [comment]
Ok, thank you, I will try use provided input from the link as the prototype.
