### ISSUE TITLE
Chromium-ozone-wayland content_shell compilation error.

### ISSUE THREAD

**Issue by pl161187smi** [OSSystems/meta-browser#231]
Hello all, I was try to build **chromium-ozone-wayland_72.0.3626.121.bb** in content shell:
`do_compile() {
	ninja -v ${PARALLEL_MAKE} chrome chrome_sandbox chromedriver content_shell
}`
But obtain the error. Firstly related to testing fonts, and I manually copy fonts but now build end with error :
`In file included from ../../chrome/browser/ui/views/overlay/overlay_window_views.cc:5:
../../chrome/browser/ui/views/overlay/overlay_window_views.h:205:47: error: 'kEndOfVideo' was not declared in this scope`
Maybe I do need to specify some GN_ARGS arguments specific to the content shell ?
For me need minimalistic one window browser, I also try run in kiosk node but it looks like full-screen mode but for me need NOT full-screen mode, I try to set window size but after start window automatic resized to full screen without window.

**Comment by rakuco** [comment]
Over to @msisov

**Comment by msisov** [comment]
Do you some any other additional gn args?

**Comment by otavio** [comment]
Closing due inactiveness.
