### ISSUE TITLE
Creating the firefox profile with yocto

### ISSUE THREAD

**Issue by malterik** [OSSystems/meta-browser#248]
Hi,

I'm currently creating an image with yocto for a read only device, that uses firefox. I have some plugins and configuration things that I want to have on my target, which belong into the firefox profile (~/.mozilla/firefox/...). Currently I create the profile directory on a running device and then put it in a tar archive and use that in a custom yocto recipe to unpack it in the rootfs. It works fine, but I'm wondering if there are other ways to do this? My way seems more like a workaround for me.

Regards,
Erik

**Comment by otavio** [comment]
Indeed, this seems a little cumbersome but I don't see many alternatives. It'd be nice if Firefox could use a "template" for the initial profile as it'd allow you to bootstrap it.
