### ISSUE TITLE
chromium-ozone-wayland-73.0.3683.103-r0 do_compile failed

### ISSUE THREAD

**Issue by kraj** [OSSystems/meta-browser#251]
I am seeing below failures on qemux86-64 using gcc as default compiler. Its using master of oe-core.

https://errors.yoctoproject.org/Errors/Details/237664/

**Comment by kraj** [comment]
@msisov @rakuco let me know if you need more info than above.

**Comment by msisov** [comment]
@kraj it's the wayland scanner problem. What is your env?

**Comment by rakuco** [comment]
I'm pretty sure this is #241

**Comment by kraj** [comment]
> @kraj it's the wayland scanner problem. What is your env?

to be honest I did not look but it sounded in walyand scanner python scriptish to me.

**Comment by petegriffin** [comment]
I just looked at @kraj log and it is indeed the wayland scanner issue. Temp workaround is to install wayland-scanner on your build host.

However after that workaround I get further compile errors with gcc-8.2, see log here https://pastebin.linaro.org/view/f14a2ef0

**Comment by rakuco** [comment]
Closing as a duplicate of #241.
