### ISSUE TITLE
Chromium and using XMLHttpRequest - COR problem?

### ISSUE THREAD

**Issue by cchilumbu** [OSSystems/meta-browser#254]
Hello,

I am trying to issue an HTTP request from an html5 page using JavaScript, but I keep getting a status "0" response.

When I invoke chromium with "--disable-web-security", my HTTP requests are successful (I get a response of 200 OK). 

I do not want to compromise security by using "--disable-web-security" in my final implementation.

Does anyone know the best way to solve this?

By the way, I would prefer not to use PHP or JQUERY.

Thank you.

**Comment by rakuco** [comment]
This doesn't seem to be caused by the Chromium recipe, so it's likely either a bug in your code or in Chromium. If you think it's a Chromium bug, please file a bug in https://bugs.chromium.org with a test case.
