### ISSUE TITLE
Dropping "thud" from LAYERSERIES_COMPAT?

### ISSUE THREAD

**Issue by rakuco** [OSSystems/meta-browser#324]
One of the things we discussed in #237 was which branches to support in Chromium. @otavio mentioned supporting master, stable and oldstable (the latter for a transition period) in https://github.com/OSSystems/meta-browser/issues/237#issuecomment-474377057

"zeus" was released about a week ago, so if I understood everything correctly we should consider supporting only zeus and warrior, and consider dropping support for thud after a while. Should we do that in November? December?

**Comment by kraj** [comment]
Drop thud as soon as we start with Zeus builds
