### ISSUE TITLE
chromium: proposal to add CVE_PRODUCT

### ISSUE THREAD

**Issue by msisov** [OSSystems/meta-browser#325]
Hi,

One of our clients that uses the meta-browser recipe asked if we could add 

`CVE_PRODUCT = "chromium:chromium google:chrome"`

to the recipe. Any objections or suggestions for this?

**Comment by otavio** [comment]
Not  really. Mind to do the same to firefox?

**Comment by msisov** [comment]
sure. I'll send a pr then
