### ISSUE TITLE
When trying to click a <select> element in the page, xdg_pop() fails

### ISSUE THREAD

**Issue by jkarnataki** [OSSystems/meta-browser#333]
chromium_ozone_wayland version 75.0.3770.142

In any HTML page which has a *select* element, touching the select element should bring a popup, but there is a DCHECK failure at:

ui/ozone/platform/wayland/host/wayland_window.cc
WaylandWindow::CreateXdgPopup()
DCHECK(parent_window_ && !xdg_popup_);

[wayland_window_crash.txt](https://github.com/OSSystems/meta-browser/files/3890841/wayland_window_crash.txt)

**Comment by rakuco** [comment]
Chromium 75 is pretty old by Chromium standards, and especially so by chromium-ozone-wayland standards. Can you reproduce this with the latest release in this tree?

**Comment by msisov** [comment]
please reopen if the issue still exists in the latest release.

**Comment by jkarnataki** [comment]
Issue is reproducible in 78.0.3904.108.

**Comment by msisov** [comment]
actually, we have this bug reported in the crbug. We'll work on it as soon as possible.
