### ISSUE TITLE
chromium(-x11) fails to build with pulesaudio version >= 13

### ISSUE THREAD

**Issue by schnitzeltony** [OSSystems/meta-browser#341]
With recent oe-core I get errors as

> gen/media/audio/pulse/pulse_stubs.cc:280:6: error: conflicting types for 'pa_context_errno'
> int  pa_context_errno(pa_context *c) {
>      ^

Seems pulseaudio did change their API and added some `const` here and there.
Found [1] but this won't do for us because it would break builds for pulseaudio < V13.

Anybody?

[1] https://694896.bugs.gentoo.org/attachment.cgi?id=590500

**Comment by rakuco** [comment]
This is being fixed in #337

**Comment by schnitzeltony** [comment]
Although I saw that one I did not notice that it contains pulseaudio fix.

Thanks!
