### ISSUE TITLE
Firefox fails to build on aarch64, zeus branch

### ISSUE THREAD

**Issue by MikeLooijmans** [OSSystems/meta-browser#355]
With "zeus" branch of OE, and today's "master" of meta-browser and meta-rust, the build fails with the following message. It did compile okay on warrior a few weeks ago.

|  9:24.86 media/webrtc/trunk/webrtc/api/audio_codecs/ilbc/audio_decoder_ilbc_gn
|  9:26.03 error[E0506]: cannot assign to `self.input.cached_token` because it is borrowed
|  9:26.03    --> /usr/src/debug/firefox/68.0esr-r0/firefox-68.0/third_party/rust/cssparser/src/parser.rs:584:17
|  9:26.03     |
|  9:26.03 559 |     pub fn next_including_whitespace_and_comments(&mut self) -> Result<&Token<'i>, BasicParseError<'i>> {
|  9:26.03     |                                                   - let's call the lifetime of this reference `'1`
|  9:26.03 ...
|  9:26.03 572 |             Some(ref cached_token)
|  9:26.03     |                  ---------------- borrow of `self.input.cached_token` occurs here
|  9:26.03 ...
|  9:26.03 584 |                 self.input.cached_token = Some(CachedToken {
|  9:26.03     |                 ^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.input.cached_token` occurs here
|  9:26.03 ...
|  9:26.03 596 |         Ok(token)
|  9:26.03     |         --------- returning this value requires that `self.input.cached_token.0` is borrowed for `'1`
|  9:26.15 media/webrtc/trunk/webrtc/api/audio_codecs/ilbc/audio_encoder_ilbc_gn
|  9:26.49 error: aborting due to previous error
|  9:26.49 For more information about this error, try `rustc --explain E0506`.
|  9:26.51 error: could not compile `cssparser`.

**Comment by cosmo0920** [comment]
I'd also hit the issue.

Using Rust 1.37.0 can be avoided compilation failure.

I'm using the following settings in local.conf:

```
PREFERRED_VERSION_rust-native ?= "1.37.0"
PREFERRED_VERSION_rust-cross-aarch64 ?= "1.37.0"
PREFERRED_VERSION_rust-llvm-native ?= "1.37.0"
PREFERRED_VERSION_libstd-rs ?= "1.37.0"
PREFERRED_VERSION_cargo-native ?= "1.37.0"

```

**Comment by MastaG** [comment]
Thanks!
