### ISSUE TITLE
chromium-ozone-wayland webrtc sound issue.

### ISSUE THREAD

**Issue by simonchen007** [OSSystems/meta-browser#365]
hello,

There is a bug in chromium-ozone-wayland-79.0.3945.117 , 
Things is that, once the pulseaudio service restarted, the chromium-ozone-wayland  has no audio in webrtc.
the only resoleve way is restart the chromium-ozone-wayland too when  pulseaudio service restarted.  The strange thing is it has audio when play mp3 files without chromium-ozone-wayland restarted, but webrtc has no audio unless restart the chromium-ozone-wayland.

how can I tracing and fix this bug ?

**Comment by msisov** [comment]
I'm not a webrtc expert. Please report to upstream. Does it also happen with chromium-x11?

**Comment by simonchen007** [comment]
I run chromium-x11 in Debian before, this not happen.

> I'm not a webrtc expert. Please report to upstream. Does it also happen with chromium-x11?

**Comment by msisov** [comment]
Can you please report to upstream and share the link here? The meta-browser repo  is not the right place for this kind of things.

**Comment by simonchen007** [comment]
I have resolved this issue with another way -- just cancel the pid of pulseaudio ,  it works currently.

**Comment by msisov** [comment]
Ok. Thanks for letting us know.
