### ISSUE TITLE
How to make firefox stable

### ISSUE THREAD

**Issue by bkauler** [OSSystems/meta-browser#41]
I am not setup to do a pull request, so I will leave it to you guys to implement this, or not.

I compiled firefox in OE, but it crashed at first startup. Subsequently started, but very unstable.
I also compiled seamonkey, which has the same code base, and it exhibited exactly the same symptoms.

I have chased down all of the reasons for the instability.
Firstly, do not use system cairo, as advised by LFS:
http://www.linuxfromscratch.org/blfs/view/7.9/xsoft/firefox.html

Quoting:

> # From firefox-40, using system cairo causes firefox to crash
> # frequently when it is doing background rendering in a tab.
> #ac_add_options --enable-system-cairo

That affects stability while running. The crash at first startup, and also instability while running (crashing on certain sites, such as sourceforge.net), is due to using system icu, which is version 58.2.
You need to use the internal icu, OR, use icu 56.1 from krogoth.

What I did is get the icu 56.1 recipe from krogoth, into my layer, and I also added patches from seamonkey's internal icu -- that is seamonkey 2.48b1. Both seamonkey and firefox internally use icu 56.1.

What I cannot tell you is whether those icu patches from seamonkey are a factor in the stability or not. 

Anyway, I used icu from krogoth and the icu patches from seamonkey, and internal cairo, compiled seamonkey, and it has been rock solid.

Now, sqlite. firefox cannot use system sqlite, because it can been configured with the wrong options. This is a detail that has been sorted out by distros such as Ubuntu, but not by OE. But, I will probably have to post to openembedded-core github about that.

Regards,
Barry

**Comment by ashie** [comment]
> Firstly, do not use system cairo, as advised by LFS:

Hmm, it's interesting.
I also found a similar description in Debian's package:

debian/changelog:
```
iceweasel (26.0-1) experimental; urgency=low
  ...
  * debian/control*, debian/xulrunner.mozconfig.in: Build with the in-tree
    cairo. I think it's time to admit that there are too many issues with
    system cairo.
```

Probably this is the latest change for `--enable-system-cairo'.

Fedora also disables it.
