### ISSUE TITLE
Adding/buildin chrome extension

### ISSUE THREAD

**Issue by nandra** [OSSystems/meta-browser#418]
Hi,

I'm using chromium from this meta layer and all seems to be fine. I plan to add some extension but automatic install fails due reasons (root user, guest account, various restrictions, etc.. Is there any way how to easily add extension to compile chrome? Or I need to do special recipe which will fetch extension and somehow install to proper path for chromium to be able to see it? Thanks for any info.

**Comment by r1mikey** [comment]
What we do is use a separate recipe to install our extensions.

The crx file and associate $HASH.json file simply need to be installed to `${D}/usr/share/chromium/extensions`.

**Comment by nandra** [comment]
@r1mikey thanks a lot. I'll give a try. :+1:

**Comment by nandra** [comment]
Thanks that did the trick. Closing.
