### ISSUE TITLE
Firefox fails to compile

### ISSUE THREAD

**Issue by MastaG** [OSSystems/meta-browser#467]
I'm trying to build Firefox with todays master branches of openembedded-core/meta-clang/meta-rust/meta-browser.
But it fails somewhere with:
```
|  5:36.47    Compiling gkrust v0.1.0 (/home/mastag/src/odroid-oe-core/build/tmp/work/cortexa15t2hf-neon-vfpv4-oe-linux-gnueabi/firefox/68.9.0esr-r0/firefox-68.9.0/toolkit/library/rust)
|  5:36.49 error: options `-C embed-bitcode=no` and `-C lto` are incompatible
|  5:36.51 error: could not compile `gkrust`
```

Any ideas?

**Comment by MastaG** [comment]
Nevermind.
https://hg.mozilla.org/releases/mozilla-esr68/rev/fb557eeb5977

Perhaps the firefox version could be bumped to ESR 78 instead?

**Comment by kraj** [comment]
> Nevermind.
> https://hg.mozilla.org/releases/mozilla-esr68/rev/fb557eeb5977
> 
> Perhaps the firefox version could be bumped to ESR 78 instead?

do we need this patch here ? if so please send a PR
