### ISSUE TITLE
testing upgrade with hardknott/master

### ISSUE THREAD

**Issue by yifan19** [OSSystems/meta-browser#497]
as we approach a release, can we switch to hardknott 3.3 testing.
https://github.com/OSSystems/meta-browser/pull/494

issue first mentioned
https://github.com/OSSystems/meta-browser/issues/463#issuecomment-795152287

I think it makes more sense to at least run 1 master build too

**Comment by rakuco** [comment]
cc @msisov who usually does the test-builds when updating the recipe.

**Comment by msisov** [comment]
I will try to find time to update the config of our bot.

**Comment by msisov** [comment]
still in my todo, but i'll close this
