### ISSUE TITLE
How can I get the newest chromium version?

### ISSUE THREAD

**Issue by jwzl** [OSSystems/meta-browser#508]
I found #507  fixed the freezen issue, but I use the yocto zeus.
and I found the  LAYERSERIES_COMPAT_chromium-browser-layer = "dunfell gatesgarth hardknott"

and not found zeus.
and how can I apply the M90 chromium in my zeus yocto project?

thank you very much!

**Comment by msisov** [comment]
It should probably compile fine if you just add zeus to the list of compatible layers.

**Comment by jwzl** [comment]
I meet the issue:
 ../../base/containers/checked_iterators.h:241:8: error: explicit specialization of undeclared template struct '__is_cpp17_contiguous_iterator'

**Comment by msisov** [comment]
are you using clang? you can try to use one from the master branch.. who knows..maybe it will work :) otherwise, you'll have to fix these compilation failures.

**Comment by msisov** [comment]
i think this can be closed

**Comment by jwzl** [comment]
I build the chromium okay, but generate image failed:
 imx-image-full-1.0-r0 do_rootfs: Postinstall scriptlets of ['chromium-ozone-wayland'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.
