### ISSUE TITLE
chromium: [zeus] how to Enable vpu in chromium on imx8 mini 

### ISSUE THREAD

**Issue by jwzl** [OSSystems/meta-browser#524]
how to Enable vpu in chromium on imx8 mini?
the video  decoder is sw and not for hw by default, and how can I enable it?

**Comment by msisov** [comment]
Chromium supports V4L2 (ChromeOS only IIRC) and VA-API (the current recipe has a patch that enables that for Ozone/Wayland). VA-API may not be supported by imx8 as it's either required to support VA-API, vpdau or nvidia drivers according to https://wiki.archlinux.org/title/Hardware_video_acceleration#Comparison_tables . So, you'll have to implement video decoding path that is supported by imx8.
