### ISSUE TITLE
chromium: update to M92

### ISSUE THREAD

**Issue by msisov** [OSSystems/meta-browser#526]
Stable release announcements since our latest update:
(No announcement yet. The releases happens on 20th of July. see https://chromiumdash.appspot.com/schedule)

Targets and platforms we need to check:

**chromium-x11:**
- dunfell, clang, MACHINE="intel-core2-32"
- dunfell, clang, MACHINE="intel-corei7-64"
- dunfell, clang, MACHINE="raspberrypi3"
- gatesgarth, MACHINE="raspberrypi3"

**chromium-ozone-wayland:**

- dunfell, clang, MACHINE="intel-corei7-64"
- dunfell, clang, MACHINE="qemuarm64"
- gatesgarth, clang, MACHINE="raspberrypi3"
- dunfell, clang, MACHINE="m3ulcb"

+ hardknott branches.

**Comment by rakuco** [comment]
Fixed by #531.
