### ISSUE TITLE
chromium: Consider using bundled FreeType copy

### ISSUE THREAD

**Issue by rakuco** [OSSystems/meta-browser#569]
Chromium project members contribute to FreeType itself, and are always actively tracking the latest upstream versions (include pre-release ones), depending on features included there and staying up-to-date with security issues.

This makes it difficult for us to get Chromium to build on multiple branches, including old ones like dunfell, where the FreeType version might lag behind what Chromium expects by quite a bit.

So far this means we've had commits like ac9d7200001434e692abad4052d5f34ba48f25e9 (with a patch that needs to be updated on every Chromium update), but according to #568 it no longer seems to be enough.

I'd like us to consider passing `use_system_freetype=false` to GN and using Chromium's own FreeType copy.

**Comment by rakuco** [comment]
@kraj @msisov @shr-project @otavio

**Comment by kraj** [comment]
> Chromium project members contribute to FreeType itself, and are always actively tracking the latest upstream versions (include pre-release ones), depending on features included there and staying up-to-date with security issues.
> 
> This makes it difficult for us to get Chromium to build on multiple branches, including old ones like dunfell, where the FreeType version might lag behind what Chromium expects by quite a bit.
> 
> So far this means we've had commits like [ac9d720](https://github.com/OSSystems/meta-browser/commit/ac9d7200001434e692abad4052d5f34ba48f25e9) (with a patch that needs to be updated on every Chromium update), but according to #568 it no longer seems to be enough.
> 
> I'd like us to consider passing `use_system_freetype=false` to GN and using Chromium's own FreeType copy.

I guess this is the approach we have to follow as chromium abstracts itself from platform more and more. Are there more liba that we should consider at this Time

**Comment by rakuco** [comment]
> Are there more liba that we should consider at this Time

I don't think so, at least. `chromium-unbundle.inc` only unbundles flac, libjpeg and libxslt at the moment, and I don't see other patches for third-party libraries in `files/`.

**Comment by kraj** [comment]
Ok looks good to me let’s start using bundled version
