### ISSUE TITLE
chromium-ozone-wayland 96.0.4664.45 --in-process-gpu shows strange border when window is not maximized.

### ISSUE THREAD

**Issue by MastaG** [OSSystems/meta-browser#591]
Hi @msisov 

Previously you had fixed the use of --in-process-gpu for wayland when drivers do not support dmabuf (or any other modern features).
After upgrading to 96.0.4664.45 it doesn't seem to work any longer.
It now renders a black border around the window, however for some strange reason when taking a screenshot, it will fill the border with garbage.
![Screenshot from 2021-11-29 14-42-23](https://user-images.githubusercontent.com/15012115/143880030-670a9841-c837-40f9-93cb-3347f41a098d.png)
.
I'm running it on Fedora 35 with: ```--use-gl=egl --ozone-platform=wayland --no-sandbox --ignore-gpu-blocklist --ignore-gpu-blacklist --in-process-gpu```

Full report:
[report.txt](https://github.com/OSSystems/meta-browser/files/7618578/report.txt)

**Comment by MastaG** [comment]
Update:

When adding: ```--enable-native-gpu-memory-buffers --enable-gpu-rasterization --enable-impl-side-painting``` it seems to be fully accelerated and snappy again.

However the strange thick border remains.
It seems to be the the edge of the window which you can hover your mouse cursor over to resize it.

**Comment by MastaG** [comment]
Hi @msisov 
Do you have any idea what could be the cause?
I am building with gtk support enabled btw (it's disabled by default for some reason), I could try to do a build without it.

**Comment by msisov** [comment]
Sorry, I didn’t have time to work on this issue due to higher priority tasks. 

I wonder you can try chromium from the main (master) branch instead? There were some issues with frame insets. Maybe, this issue is one of those and have already been fixed.

**Comment by MastaG** [comment]
Yep, it's fixed by using the latest git version.
Let's hope it will be backported soon.
