### ISSUE TITLE
VA-API patch no longer working

### ISSUE THREAD

**Issue by hedgepigdaniel** [OSSystems/meta-browser#592]
This patch: `0001-ozone-add-va-api-support-to-wayland.patch`

No longer works, as a result of https://chromium-review.googlesource.com/c/chromium/src/+/3141878

However, I can confirm that it does work after adding `properties->supports_vaapi = true;` to `ozone_platform_wayland.cc`, as it is done for X11. `VdaVideoDecoder` is used according to the dev tools and `intel_gpu_top` shows usage of `Video`.

**Comment by msisov** [comment]
Oh. Good catch! Thanks
