### ISSUE TITLE
how can i run google-chrome

### ISSUE THREAD

**Issue by kt791004** [OSSystems/meta-browser#60]
please help me. i can not run chrome.

meta-browser : morty  with raspberrypi 3 patch
meta-raspberrypi : morty
poky :morty

error below
display.cc(148) WaylandDisplay failed to initialize hardware
ozxonw_platform_wayland.cc(115_ failed to initialize display hardwaree

please help me to run chrome

thanks.

**Comment by otavio** [comment]
The Ozone support is old and broken; we are upgrading Chrome for the new release and the Wayland support is under active work at the upstream side. Until that, you must use X.
