### ISSUE TITLE
LINK Fails

### ISSUE THREAD

**Issue by wrani** [OSSystems/meta-browser#61]
Hi, 
Using the Morty branch , I am getting a ink failure ; 
NATIVELSBSTRING   = "universal"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "msc-sm2-imx6"
DISTRO            = "poky"
DISTRO_VERSION    = "2.2"
TUNE_FEATURES     = "arm armv7a vfp thumb neon       callconvention-hard       cortexa9"
TARGET_FPU        = "hard"
meta-poky         
meta-yocto-bsp    = "morty-amarel:b07e7bc6a479e280bd9a6a04bc0f9ffd7bd0287c"
meta              = "master:9f46ed1d63d4ec85d88e8f31efeb4a52ad0a13a2"
meta              = "morty-amarel:b07e7bc6a479e280bd9a6a04bc0f9ffd7bd0287c"
meta-oe           
meta-networking   
meta-python       = "morty-msc:5e789602f629f3e97e9d74bbf63018ceed746759"
meta-qt5.git      = "morty-msc:7128e252f83a77e04e4b53c90864f2e11677568c"
meta-oracle-java.git = "morty:f44365f02b283c3fb362dc99e2e996d3f11e356e"
meta-msc-ldk-core-recipes.git = "master:c9bb9478efc6f8bd28a6d283bc3f98306226fcbc"
meta-msc-ldk-core.git = "master:327dfb039c5a7195c4f3b78750ecc3dd66c22f97"
meta-msc-ldk-mscio.git = "master:2eef4699a0e9f509cfc67aeae87de44f87edbc89"
meta-amarel-custom.git = "develop:d41beecaf157564ba282be9a4be14c079eaeb265"
meta-freescale.git = "morty:38bd14cddf1ce325de43f1fb29f01551b48384bb"
meta-msc-ldk-lxqt.git = "master:e3a8623a884d08a57291746f7127d243a4b86880"
meta-gnome        
meta-efl          = "morty-msc:5e789602f629f3e97e9d74bbf63018ceed746759"
meta-qt5-extra.git = "morty-msc:c69df3339315e99a704c8e68ea1cb99ae41859c4"
meta-browser.git  = "morty:1569eeb9cc1b87632abbf35fbb05f4ac4eeb3987"

Initialising tasks: 100% |#####################################################################################################################################################################################################| Time: 0:00:18
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
Currently  1 running tasks (8613 of 8638)  99% |################################################################################################################ERROR: chromium-52.0.2743.76-r0 do_compile: Function failed: do_compile (log file is located at /home/amarel/msc-amarel/build/0101301-lxqt/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/chromium/52.0.2743.76-r0/temp/log.do_compile.12245)
ERROR: Logfile of failure stored in: /home/amarel/msc-amarel/build/0101301-lxqt/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/chromium/52.0.2743.76-r0/temp/log.do_compile.12245
Log data follows:
| DEBUG: Executing shell function do_compile
| ninja: Entering directory `/home/amarel/msc-amarel/build/0101301-lxqt/tmp/work/cortexa9hf-neon-mx6qdl-poky-linux-gnueabi/chromium/52.0.2743.76-r0/chromium-52.0.2743.76/out/Release'
| [1/1] LINK chrome
| FAILED: chrome
| arm-poky-linux

Ideas ?

**Comment by otavio** [comment]
Memory; it needs 16GiB of RAM for linking.
