### ISSUE TITLE
Error in progress of building core-image-weston with meta-chromium and meta-clang (dunfell branch )

### ISSUE THREAD

**Issue by MonsieurHBA** [OSSystems/meta-browser#612]
Hello guys :+1: 
So is that will affect my image or chromium will not work after build ?

![Screenshot from 2022-03-02 06-24-26](https://user-images.githubusercontent.com/91086501/156327804-f044635c-e3f2-411a-b03d-a3a961027c28.png)

**Comment by MonsieurHBA** [comment]
![Error](https://user-images.githubusercontent.com/91086501/156342952-d606668b-3a84-4812-9ee8-e88fe49c0eb2.png)
this my config file

**Comment by rakuco** [comment]
Sorry, but we don't maintain that recipe and can't help you further with that. Please check who the maintainer of that recipe is and what the instructions for filing bugs is. Just one side note: meta-clang needs to track the `clang12` branch, not the `dunfell` branch. Good luck!

**Comment by kraj** [comment]
yeah I think we need to fix other `dunfell` layers to build with clang12. 
@MonsieurHBA can you add
```
CFLAGS:append:pn-kbd:toolchain-clang = " -Wno-error"
```

to `meta-clang/conf/nonclangable.conf`
