### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by MastaG** [OSSystems/meta-browser#623]
I know this isn't really the right place to ask.
But it seems the repository lags behind quite a bit.
Chromium 100 just got released as stable and we're still stuck on v98.
Would it be better to just skip on v99 then?

**Comment by rakuco** [comment]
Over to @msisov, who usually handles the updates here.

**Comment by msisov** [comment]
I was busy with other stuff. Will do a release soon.

**Comment by MastaG** [comment]
Thanks @msisov

**Comment by msisov** [comment]
https://github.com/OSSystems/meta-browser/pull/626
