### ISSUE TITLE
/usr/lib64/chromium/chromium-bin: No such file or directory

### ISSUE THREAD

**Issue by StGale** [OSSystems/meta-browser#631]
Hello,
I have created an image YOCTO for intel core E3900 following https://github.com/intel/iotg-yocto-bsp-public/tree/e3900/master
then using meta-browser I also compiled chromium-x11 on my local.conf.
The HDDIMG on board start but when I try to run chromium the problem is this message

```
root@intel-corei7-64:~# chromium
root@intel-corei7-64:~# /usr/bin/chromium: line 51: /usr/lib64/chromium/chromium-bin: No such file or directory
```

but the file is present

```
root@intel-corei7-64:~# ls -las /usr/lib64/chromium
total 183480
     4 drwxr-xr-x  4 root root      4096 Apr 23 01:19 .
    64 drwxr-xr-x 73 root root     61440 Apr 23 11:41 ..
    20 -rwsr-xr-x  1 root root     18672 Apr 23 01:14 chrome-sandbox
  1096 -rw-r--r--  1 root root   1120967 Apr 23 01:14 chrome_100_percent.pak
  1508 -rw-r--r--  1 root root   1541344 Apr 23 01:14 chrome_200_percent.pak
157864 -rwxr-xr-x  1 root root 161700472 Apr 23 01:14 chromium-bin
     4 -rwxr-xr-x  1 root root      1962 Apr 23 01:14 chromium-wrapper
 10260 -rw-r--r--  1 root root  10505952 Apr 23 01:14 icudtl.dat
     4 drwxr-xr-x  2 root root      4096 Apr 23 01:19 locales
 11868 -rw-r--r--  1 root root  12156738 Apr 23 01:14 resources.pak
   236 -rw-r--r--  1 root root    240440 Apr 23 01:14 snapshot_blob.bin
     4 drwxr-xr-x  2 root root      4096 Apr 23 01:19 swiftshader
   548 -rw-r--r--  1 root root    558968 Apr 23 01:14 v8_context_snapshot.bin
```

can someone help me?
Thanks
Stefano

**Comment by StGale** [comment]
just to add info I cloned the warrior branch of meta-browser

**Comment by StGale** [comment]
other info:
Ubuntu 18.04 used to compile the yocto image.

during the chromium compile phase I have created two symbolic link on 
    cd ../build/tmp/work/corei7-64-poky-linux/chromium-x11/80.0.3987.132-r0/recipe-sysroot
    mv lib lib32
    ln -s lib64 lib
    cd usr/
    ln -s lib64 lib
just to prevent an error on search file 64bit on lib directory.


to complete the history, I put my local.conf:
stefano@stefano:~/ibexYoctoIntel/yocto_build/build$ cat conf/local.conf 
#
# This file is your local configuration file and is where all local user settings
# are placed. The comments in this file give some guide to the options a new user
# to the system might want to change but pretty much any configuration option can
# be set in this file. More adventurous users can look at local.conf.extended
# which contains other examples of configuration which can be placed in this file
# but new users likely won't need any of them initially.
#
# Lines starting with the '#' character are commented out and in some cases the
# default values are provided as comments to show people example syntax. Enabling
# the option is a question of removing the # character and making any change to the
# variable as required.

HOSTTOOLS += "git-lfs"

#
# Machine Selection
#
# This sets the default machine to be intel-corei7-64 if no other machine is selected:
MACHINE = "intel-corei7-64"

# This set the default kernel to linux-intel version 4.14 LTS
PREFERRED_PROVIDER_virtual/kernel = "linux-intel"
PREFERRED_VERSION_linux-intel = "4.19%"

#
# Leaf Hill BSP specific settings
#
# This sets BSP_SUBTYPE to leafhill.
# This setting is meant for Bitbake to pull the correct set of
# kernel config fragments in yocto-kernel-cache.
#
# It is not recommend to remove if your target platform is
# based on Intel Atom E3900 SoC Family.
BSP_SUBTYPE = "leafhill"

#Exclude piglit, ltp and mesa-demos packages
PACKAGE_EXCLUDE = "packagegroup-core-apl-extra"

#
# Apollo Lake Yocto BSP supports different Audio features,
# i.e. legacy HD-Audio, CAVS HD-Audio, and CAVS SSP Audio codec support.
#
# By default, this configuration will build CAVS HD-Audio feature.
# To build CAVS SSP Audio feature, uncomment the line below.
#AUDIO_FEATURES = "ssp"

#
# Machine Configuration Override for Apollo Lake platform
#
# This is a stopgap measure for configuring machine settings for Apollo Lake platform
# primarily for Pre-Production SW release until the changes are upstream to Yocto Project.
# These settings are applicable for Intel Apollo Lake project only.
# Please comment out when you are compiling for other projects.

# Uncomment when you are integrating closed source media stack
#MACHINE_HWCODECS = ""

OLD_XSERVER_X86_EXT = ""
XSERVER_X86_MATROX_MGA = ""
XSERVER_X86_ASPEED_AST = ""
MACHINE_ESSENTIAL_EXTRA_RDEPENDS_remove = "intel-microcode"
INITRD_LIVE_remove = "${DEPLOY_DIR_IMAGE}/microcode.cpio"

# Make image boot to runlevel 3 by default
APPEND = "3 snd_hda_intel.power_save=1 snd_hda_intel.power_save_controller=y scsi_mod.scan=async i915.enable_guc=2 reboot=efi console=ttyS2,115200n8 intel_iommu=on,ipu_off"

WKS_FILE = "systemd-bootdisk-microcode-custom.wks.in"
#
# User Space Configuration Override for Apollo Lake Platform
#
# Selection of jpeg package provider
PREFERRED_PROVIDER_jpeg = "jpeg"
PREFERRED_PROVIDER_jpeg-native = "jpeg-native"

# Preferred version for tpm2 packages
PREFERRED_VERSION_tpm2-tools = "4.1%"
PREFERRED_VERSION_tpm2-tss = "2.3%"
PREFERRED_VERSION_tpm2-abrmd = "2.3%"

# Enable xserver-xorg
IMAGE_INSTALL_append = " xserver-xorg"

# Enable vp8dec on gstreamer1.0-plugins-good
PACKAGECONFIG_append_pn-gstreamer1.0-plugins-good = " vpx"

# Enable msdk on gstreamer1.0-plugins-bad
PACKAGECONFIG_append_pn-gstreamer1.0-plugins-bad = " msdk"

# Enable opengl support for gstreamer plugins base
PACKAGECONFIG_append_pn-gstreamer1.0-plugins-base = "${@bb.utils.filter('DISTRO_FEATURES', 'opengl', d)}"

# Multi-libraries support is now "ON"
# Please uncomment the 4 lines below to enable multilib support.
require conf/multilib.conf
DEFAULTTUNE = "corei7-64"
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "corei7-32"

IMAGE_INSTALL_append = " lib32-glib-2.0 lib32-gcc"

IMAGE_INSTALL_append = " freeglut"

IMAGE_INSTALL_append = " openjdk-7-jre"
IMAGE_INSTALL_append = " chromium-x11"
#IMAGE_INSTALL_append = " firefox"

PACKAGE_EXCLUDE_pn-core-image-sato = "lib32-libgmp-dev lib32-xtrans-dev lib32-python3-core"
PACKAGE_EXCLUDE_pn-core-image-sato-sdk = "lib32-libgmp-dev lib32-xtrans-dev lib32-python3-core"

# Install autoconf-archive
IMAGE_INSTALL_append = " autoconf-archive"

# Install libva
IMAGE_INSTALL_append = " libva"

# Install Wayland in image
DISTRO_FEATURES_append = " wayland pam"
CORE_IMAGE_EXTRA_INSTALL += "wayland weston weston-examples"

# Install mesa glxinfo
IMAGE_INSTALL_append = " mesa-glxinfo"

# Install TPM2.0-TSS in image
IMAGE_INSTALL_append = " libtss2-mu libtss2-mu-dev libtss2-mu-staticdev libtss2-tcti-device libtss2-tcti-device-dev libtss2-tcti-device-staticdev"
IMAGE_INSTALL_append = " libtss2-tcti-mssim libtss2-tcti-mssim-dev libtss2-tcti-mssim-staticdev libtss2 libtss2-dev libtss2-staticdev"

# Install tpm2-abrmd in image
IMAGE_INSTALL_append = " tpm2-abrmd tpm2-tss tpm2-tools"

# Install MRAA and its dependencies in image
IMAGE_INSTALL_append = " nodejs swig mraa"

# Install USB-modeswitch and USB-modeswitch-data in image
IMAGE_INSTALL_append = " usb-modeswitch usb-modeswitch-data"

# Install JHI and jhi-test
IMAGE_INSTALL_append = " jhi jhi-test"

# Install IQV driver
IMAGE_INSTALL_append = " iqvlinux"

# Disable lttng modules
LTTNGMODULES_corei7-64-intel-common = ""

# Install xinitrc environment file
IMAGE_INSTALL_append = " xinit-env"

# By default, we want our OS to includes all kernel modules.
IMAGE_INSTALL_append = " kernel-modules"

# Install HDCP
IMAGE_INSTALL_append = " hdcp"

# Install opencl-headers and opencl-clhpp
IMAGE_INSTALL_append = " opencl-headers-dev opencl-clhpp-dev"
ALLOW_EMPTY_opencl-headers_pn-opencl-headers = "1"

# Install open source media driver
IMAGE_INSTALL_append = " gmmlib intel-mediasdk intel-media-driver"

# Take note that as we are building 3rd party ingredient.
# We need the LICENSE_FLAGS below.
LICENSE_FLAGS_WHITELIST += " commercial"

# Use systemd init instead of sysV init
DISTRO_FEATURES_append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"

#
# Where to place downloads
#
# During a first build the system will download many different source code tarballs
# from various upstream projects. This can take a while, particularly if your network
# connection is slow. These are all stored in DL_DIR. When wiping and rebuilding you
# can preserve this directory to speed up this part of subsequent builds. This directory
# is safe to share between multiple builds on the same machine too.
#
# The default is a downloads directory under TOPDIR which is the build directory.
#
#DL_DIR ?= "${TOPDIR}/downloads"

#
# Where to place shared-state files
#
# BitBake has the capability to accelerate builds based on previously built output.
# This is done using "shared state" files which can be thought of as cache objects
# and this option determines where those files are placed.
#
# You can wipe out TMPDIR leaving this directory intact and the build would regenerate
# from these files if no changes were made to the configuration. If changes were made
# to the configuration, only shared state files where the state was still valid would
# be used (done using checksums).
#
# The default is a sstate-cache directory under TOPDIR.
#
#SSTATE_DIR ?= "${TOPDIR}/sstate-cache"

#
# Where to place the build output
#
# This option specifies where the bulk of the building work should be done and
# where BitBake should place its temporary files and output. Keep in mind that
# this includes the extraction and compilation of many applications and the toolchain
# which can use Gigabytes of hard disk space.
#
# The default is a tmp directory under TOPDIR.
#
#TMPDIR = "${TOPDIR}/tmp"

#
# Default policy config
#
# The distribution setting controls which policy settings are used as defaults.
# The default value is fine for general Yocto project use, at least initially.
# Ultimately when creating custom policy, people will likely end up subclassing
# these defaults.
#
DISTRO ?= "poky"
# As an example of a subclass there is a "bleeding" edge policy configuration
# where many versions are set to the absolute latest code from the upstream
# source control systems. This is just mentioned here as an example, its not
# useful to most new users.
# DISTRO ?= "poky-bleeding"

#
# Package Management configuration
#
# This variable lists which packaging formats to enable. Multiple package backends
# can be enabled at once and the first item listed in the variable will be used
# to generate the root filesystems.
# Options are:
#  - 'package_deb' for debian style deb files
#  - 'package_ipk' for ipk files are used by opkg (a debian style embedded package manager)
#  - 'package_rpm' for rpm style packages
# E.g.: PACKAGE_CLASSES ?= "package_rpm package_deb package_ipk"
# We default to rpm:
PACKAGE_CLASSES ?= "package_rpm"

#
# SDK/ADT target architecture
#
# This variable specifies the architecture to build SDK/ADT items for and means
# you can build the SDK packages for architectures other than the machine you are
# running the build on (i.e. building i686 packages on an x86_64 host).
# Supported values are i686 and x86_64
#SDKMACHINE ?= "i686"

#
# Extra image configuration defaults
#
# The EXTRA_IMAGE_FEATURES variable allows extra packages to be added to the generated
# images. Some of these options are added to certain image types automatically. The
# variable can contain the following options:
#  "dbg-pkgs"       - add -dbg packages for all installed packages
#                     (adds symbol information for debugging/profiling)
#  "dev-pkgs"       - add -dev packages for all installed packages
#                     (useful if you want to develop against libs in the image)
#  "ptest-pkgs"     - add -ptest packages for all ptest-enabled packages
#                     (useful if you want to run the package test suites)
#  "tools-sdk"      - add development tools (gcc, make, pkgconfig etc.)
#  "tools-debug"    - add debugging tools (gdb, strace)
#  "eclipse-debug"  - add Eclipse remote debugging support
#  "tools-profile"  - add profiling tools (oprofile, exmap, lttng, valgrind)
#  "tools-testapps" - add useful testing tools (ts_print, aplay, arecord etc.)
#  "debug-tweaks"   - make an image suitable for development
#                     e.g. ssh root access has a blank password
# There are other application targets that can be used here too, see
# meta/classes/image.bbclass and meta/classes/core-image.bbclass for more details.
# We default to enabling the debugging tweaks.
EXTRA_IMAGE_FEATURES = "debug-tweaks tools-testapps"

#
# Additional image features
#
# The following is a list of additional classes to use when building images which
# enable extra features. Some available options which can be included in this variable
# are:
#   - 'buildstats' collect build statistics
#   - 'image-mklibs' to reduce shared library files size for an image
#   - 'image-prelink' in order to prelink the filesystem image
#   - 'image-swab' to perform host system intrusion detection
# NOTE: if listing mklibs & prelink both, then make sure mklibs is before prelink
# NOTE: mklibs also needs to be explicitly enabled for a given image, see local.conf.extended
USER_CLASSES ?= "buildstats image-mklibs image-prelink"

#
# Runtime testing of images
#
# The build system can test booting virtual machine images under qemu (an emulator)
# after any root filesystems are created and run tests against those images. To
# enable this uncomment this line. See classes/testimage(-auto).bbclass for
# further details.
#TEST_IMAGE = "1"
#
# Interactive shell configuration
#
# Under certain circumstances the system may need input from you and to do this it
# can launch an interactive shell. It needs to do this since the build is
# multithreaded and needs to be able to handle the case where more than one parallel
# process may require the user's attention. The default is iterate over the available
# terminal types to find one that works.
#
# Examples of the occasions this may happen are when resolving patches which cannot
# be applied, to use the devshell or the kernel menuconfig
#
# Supported values are auto, gnome, xfce, rxvt, screen, konsole (KDE 3.x only), none
# Note: currently, Konsole support only works for KDE 3.x due to the way
# newer Konsole versions behave
#OE_TERMINAL = "auto"
# By default disable interactive patch resolution (tasks will just fail instead):
PATCHRESOLVE = "noop"

#
# Disk Space Monitoring during the build
#
# Monitor the disk space during the build. If there is less that 1GB of space or less
# than 100K inodes in any key build location (TMPDIR, DL_DIR, SSTATE_DIR), gracefully
# shutdown the build. If there is less that 100MB or 1K inodes, perform a hard abort
# of the build. The reason for this is that running completely out of space can corrupt
# files and damages the build in ways which may not be easily recoverable.
BB_DISKMON_DIRS = "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K"

#
# Shared-state files from other locations
#
# As mentioned above, shared state files are prebuilt cache data objects which can
# used to accelerate build time. This variable can be used to configure the system
# to search other mirror locations for these objects before it builds the data itself.
#
# This can be a filesystem directory, or a remote url such as http or ftp. These
# would contain the sstate-cache results from previous builds (possibly from other
# machines). This variable works like fetcher MIRRORS/PREMIRRORS and points to the
# cache locations to check for the shared objects.
# NOTE: if the mirror uses the same structure as SSTATE_DIR, you need to add PATH
# at the end as shown in the examples below. This will be substituted with the
# correct path within the directory structure.
#SSTATE_MIRRORS ?= "\
#file://.* http://someserver.tld/share/sstate/PATH;downloadfilename=PATH \n \
#file://.* file:///some/local/dir/sstate/PATH"

#
# Qemu configuration
#
# By default qemu will build with a builtin VNC server where graphical output can be
# seen. The two lines below enable the SDL backend too. This assumes there is a
# libsdl library available on your build system.
#PACKAGECONFIG_append_pn-qemu-native = " sdl"
#PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
#ASSUME_PROVIDED += "libsdl-native"


# CONF_VERSION is increased each time build/conf/ changes incompatibly and is used to
# track the version of this file when it was generated. This can safely be ignored if
# this doesn't mean anything to you.
CONF_VERSION = "1"

# Enable the security flags as per SDL 4.0 requirement
require conf/distro/include/security_flags.inc
SECURITY_CFLAGS = "-fstack-protector-strong -pie -fpie -fPIC -D_FORTIFY_SOURCE=2 -O2 -Wformat -Wformat-security"
SECURITY_NO_PIE_CFLAGS = "-fstack-protector-strong -D_FORTIFY_SOURCE=2 -O2 -Wformat -Wformat-security"
SECURITY_LDFLAGS = "-Wl,-z,relro,-z,now,-z,noexecstack"
AUDIO_FEATURES = "ssp"

**Comment by rakuco** [comment]
The "no such file or directory" error message sometimes means you're trying to run an executable that's not supported (a 32-bit binary in a 64-bit installation that does not support it, for example).

* Are you doing a regular 64-bit build targeting a 64-bit platform?
* chromium-x11 80.0.3987.132 is _very_ old. Would it be possible to update the recipe to a more recent version? Similarly, the warrior branch has not been supported upstream for years, is there any chance of moving to a supported branch?
* What happens if you manually run the `chromium-bin`? Does it still show up the same "no such file or directory" message?

**Comment by StGale** [comment]
hi found a solution disabling the multi libraries

# Multi-libraries support is now "ON"
# Please uncomment the 4 lines below to enable multilib support.
require conf/multilib.conf
DEFAULTTUNE = "corei7-64"
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "corei7-32"

comment out the 4 lines on default local.conf.sample after checkout MR5-B-04

https://github.com/intel/iotg-yocto-bsp-public/tree/e3900/master

**Comment by rakuco** [comment]
OK, thanks. I'm closing this issue since it doesn't seem to be a meta-chromium bug.
