### ISSUE TITLE
chromium: Update to 106.0.5249.119 

### ISSUE THREAD

**Issue by rwmacleod** [OSSystems/meta-browser#669]
https://chromereleases.googleblog.com/2022/10/stable-channel-update-for-desktop_11.html

I won't get to this for a few weeks so if anyone else is interested, please let us all know.

**Comment by rakuco** [comment]
@msisov any chance of you being able to do it before Randy?

**Comment by msisov** [comment]
Just wanted to open this issue and noticed Randy has already opened one. I'll take this.
