### ISSUE TITLE
Please submit meta-chromium and meta-firefox to layerindex

### ISSUE THREAD

**Issue by moto-timo** [OSSystems/meta-browser#756]
The layerindex has been unable to  perform updates since the split to having meta-chromium and meta-firefox subdirectories.

https://layers.openembedded.org/layerindex/updates/37925/
ERROR: conf/layer.conf not found for layer meta-browser - is subdirectory set correctly?

Updates are now disabled for the meta-browser entry, please submit meta-chromium and meta-firefox as new layers.

layerindex is not psychic.

**Comment by kraj** [comment]
done

**Comment by moto-timo** [comment]
meta-chromium "Published" so it will hopefully be in the next update within the next hour (roughly three hours between update runs)

**Comment by moto-timo** [comment]
meta-firefox needs to be submitted separately?

**Comment by moto-timo** [comment]
Nevermind. Also "Published".

**Comment by moto-timo** [comment]
I'll report back and close this issue when the updates are complete and no errors.

**Comment by moto-timo** [comment]
Passed updates (with a typical annoying warning that is mostly universal right now)
https://layers.openembedded.org/layerindex/updates/37926/

https://layers.openembedded.org/layerindex/branch/master/layer/meta-chromium/
https://layers.openembedded.org/layerindex/branch/master/layer/meta-firefox/

Thank you @kraj
